import { precacheAndRoute } from 'workbox-precaching';
import { registerRoute } from 'workbox-routing';
import { StaleWhileRevalidate, CacheFirst, NetworkFirst } from 'workbox-strategies';
import { ExpirationPlugin } from 'workbox-expiration';
import { CacheableResponsePlugin } from 'workbox-cacheable-response';

// Precache all assets generated by the build process
precacheAndRoute(self.__WB_MANIFEST);

// Cache images from Cloudinary
registerRoute(
  ({ url }) => url.origin === 'https://res.cloudinary.com',
  new CacheFirst({
    cacheName: 'cloudinary-images',
    plugins: [
      new ExpirationPlugin({
        maxEntries: 50,
        maxAgeSeconds: 30 * 24 * 60 * 60, // 30 Days
      }),
      new CacheableResponsePlugin({
        statuses: [0, 200],
      }),
    ],
  })
);

// Cache API requests that are suitable for stale-while-revalidate (e.g., products)
registerRoute(
  ({ url }) => url.pathname.startsWith('/api/products') || url.pathname.startsWith('/api/shipping-fees'),
  new StaleWhileRevalidate({
    cacheName: 'api-cache',
  })
);

// Use NetworkFirst for user-specific data to ensure freshness when online
registerRoute(
  ({ url }) => url.pathname.startsWith('/api/auth/me') || url.pathname.startsWith('/api/orders'),
  new NetworkFirst({
    cacheName: 'user-data-cache',
    plugins: [
      new ExpirationPlugin({
        maxEntries: 10,
      }),
    ],
  })
);

// Offline fallback for SPA routing
self.addEventListener('install', (event) => {
  const offlinePage = new Response(
    '<html><body><h1>You are offline</h1><p>Please check your internet connection.</p></body></html>',
    { headers: { 'Content-Type': 'text/html' } }
  );
  event.waitUntil(
    caches.open('offline-fallback').then((cache) => cache.put('offline', offlinePage))
  );
});